name: Auto Add Issue/PR to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    name: Add to GitHub Project #5
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/jiramatk-masque/projects/5
          github-token: ${{ secrets.GH_TOKEN }}
